spring.application.name=foodhub

# ==========================
# CONFIGURACIÓN DEL PUERTO (RAILWAY)
# ==========================
server.port=${PORT:8080}

# ==========================
# BASE DE DATOS (MARIADB)
# ==========================
# Usa los datos locales de respaldo si no encuentra las variables de Railway
spring.datasource.url=jdbc:mariadb://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQL_DATABASE:foodhub}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:FoodHub123}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# CONFIGURACIÓN DEL CORREO
# ==========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luisfinix12345@gmail.com
spring.mail.password=kahg kloe nfpb jmgm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
